name: Daily Football Picks

on:
  schedule:
    # Ajusta para que coincida con tus 22:00 hora local
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install distutils
        run: sudo apt-get update && sudo apt-get install -y python3-distutils

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predictor
        run: python main.py
