name: Nightly Football Prediction

on:
  schedule:
    - cron: '6 6 * * *'
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: 7852899849:AAHGe4o-19s0wQThBpIqDD0gQThBpIqDD0gJ_F1ZctaYSw
      TELEGRAM_CHAT_ID: 8083268965
      DB_URL: sqlite:///data/predictions.db

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

      - run: ls -R .

      - run: |
          pwd
          python --version

      - run: python src/main.py
