name: Nightly Football Prediction

# Ejecutar cada día a las 22:00 hora local (UTC-8 = 06:00 UTC siguiente día)
on:
  schedule:
    - cron: '6 6 * * *'       # 06:00 UTC = 22:00 PST anterior
  workflow_dispatch:          # Permite ejecución manual

jobs:
  predict:
    runs-on: ubuntu-latest

    # Variables de entorno (ya con tu token público)
    env:
      TELEGRAM_BOT_TOKEN: 7852899849:AAHGe4o-19s0wQThBpIqDD0gJ_F1ZctaYSw
      TELEGRAM_CHAT_ID: 8083268965
      DB_URL: sqlite:///data/predictions.db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run prediction script
        run: python src/main.py
